### ISSUE TITLE
a n64 request 

### ISSUE THREAD

**Issue by dananothername** [CrashOveride95/n64sdkmod#10]
can you post the cave story n64 rom
i can't build it 
or why do i need to it just rom work in any emulator 
even if it's not completed i really need it for collection

**Comment by CrashOveride95** [comment]
I don't have any cave story anything in this repository and have never developed a cave story port so closing this

**Comment by dananothername** [comment]
https://github.com/CrashOveride95/Cave-Story-N64
you did 
you just didn't offer a way to contact you there

**Comment by CrashOveride95** [comment]
I believe that was a fork of someone else's repository who seems to have deleted their account

**Comment by CrashOveride95** [comment]
![Screenshot_20221130-095059.png](https://user-images.githubusercontent.com/40003130/204827667-881c32f4-ba41-4d39-9c94-08de3e3bc200.png)

**Comment by dananothername** [comment]
and He refuses to respond on YouTube 
you know something about n64 
does his repository Buildable
