### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by Fridux** [CrashOveride95/n64sdkmod#8]
The demos have licenses, but I couldn't
find any license for the binaries (like the compiler) in this SDK!

It would be nice if a license was added, so that developers
could see what they can do and what not with this SDK.

**Comment by CrashOveride95** [comment]
The compiler's source is just a shellscript, where i download the source from GNU and build the compiler package. That can be assumed to be GPL, as I based it off n64chain which is GPL.
Almost everything in this kit is taken from the official devkit, and obviously I cannot relicense it, I didn't write it.

**Comment by Fridux** [comment]
Thank you!
Then I can now continue programming!
